[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "psutil>=7.0.0",
    "pycodestyle>=2.13.0",
    "requests>=2.32.3",
    "websocket-client>=1.8.0",
]
